version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alva_clean_api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - alva_clean_network

  crm:
    build:
      context: ../AlvaCleanCRM
      dockerfile: Dockerfile
    container_name: alva_clean_crm
    ports:
      - "5002:8080"
      - "5003:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://alva_clean_api:8080
    depends_on:
      - api
    networks:
      - alva_clean_network

networks:
  alva_clean_network:
    driver: bridge
